Conteggi e misure significative rispetto a CIG con premialità e quote/deroghe

In [1]:
import pandas as pd 
import numpy as np

In [2]:
tmp_finale1= pd.read_csv("tmp_finale_1.csv", sep=';')

In [3]:
tmp_finale1

CIG  importo_complessivo_gara CLASSE_IMPORTO  cod_mis_premiale  \
0       A0011137E1                  21131.90          BASSA               NaN   
1       A0011137E1                  21131.90          BASSA               NaN   
2       A0011137E1                  21131.90          BASSA               NaN   
3       A0011137E1                  21131.90          BASSA               NaN   
4       A0011137E1                  21131.90          BASSA               NaN   
...            ...                       ...            ...               ...   
273874  A001EFE42A                 149800.00          MEDIA               1.0   
273875  A000A6FCFD                   1262.42          BASSA               NaN   
273876  99600068F5                 101732.97          MEDIA               NaN   
273877  9946229FCF                 668715.94          MEDIA               NaN   
273878  A040E713C1                   5688.00          BASSA               NaN   

                                          misura_premiale CATEGORIA  \
0                                                     NaN       NaN   
1                                                     NaN       NaN   
2                                                     NaN       NaN   
3                                                     NaN       NaN   
4                                                     NaN       NaN   
...                                                   ...       ...   
273874  NEI TRE ANNI ANTECEDENTI LA DATA DI SCADENZA D...  GENERALE   
273875                                                NaN       NaN   
273876                                                NaN       NaN   
273877                                                NaN       NaN   
273878                                                NaN       NaN   

       flag_quote  quota_femminile  quota_giovanile  cod_mot_deroga  ...  \
0               N              NaN              NaN             1.0  ...   
1               N              NaN              NaN             1.0  ...   
2               N              NaN              NaN             1.0  ...   
3               N              NaN              NaN             1.0  ...   
4               N              NaN              NaN             1.0  ...   
...           ...              ...              ...             ...  ...   
273874          S              NaN              NaN             NaN  ...   
273875          N              NaN              NaN             8.0  ...   
273876          N              NaN              NaN             8.0  ...   
273877          N              NaN              NaN             1.0  ...   
273878          N              NaN              NaN             8.0  ...   

       PROVINCIA                  COMUNE ANNO_DECISIONE data_pubblicazione  \
0        IMPERIA                SAN REMO         2019.0         2023-08-02   
1        IMPERIA                 IMPERIA         2019.0         2023-08-02   
2        IMPERIA  SAN BARTOLOMEO AL MARE         2019.0         2023-08-02   
3        IMPERIA                   CERVO         2019.0         2023-08-02   
4         SAVONA                  ANDORA         2019.0         2023-08-02   
...          ...                     ...            ...                ...   
273874   BERGAMO              OSIO SOTTO         2022.0         2023-08-03   
273875   FERRARA                 COPPARO         2021.0         2023-08-01   
273876   CATANIA                 SCORDIA         2022.0         2023-08-14   
273877       NaN                     NaN            NaN         2023-07-13   
273878   SALERNO    MERCATO SAN SEVERINO         2021.0         2023-08-21   

       COSTO_PROGETTO  IMPORTO_FINANZIAMENTO CODICE_MISSIONE  \
0          29500000.0             29500000.0              M2   
1          29500000.0             29500000.0              M2   
2          29500000.0             29500000.0              M2   
3          29500000.0             29500000.0              M2   
4          29500000

In [4]:
check = tmp_finale1[tmp_finale1['CATEGORIA']=='GENERE'].drop_duplicates(subset='CIG')
prem_cig = check.shape[0]
tot_cig = tmp_finale1['CIG'].nunique()
prem_perc = np.round(prem_cig/tot_cig*100,2)

In [5]:
print("Ci sono", prem_cig,"CIG unici con almeno una premialità di genere, su",tot_cig ,"CIG unici.")
print("In percentuale:",prem_perc,'%')

Ci sono 5595 CIG unici con almeno una premialità di genere, su 170481 CIG unici.
In percentuale: 3.28 %


Ci sono 5595 CIG unici con almeno una premialità di genere, su 170481 CIG unici.
In percentuale: 3.28 %

domande
se c'è N non c'è premialità? no
nn = p07rid[p07rid['flag_quote']=='N']
nn[nn['misura_premiale'].notna()]['misura_premiale'].nunique()

In [6]:
check1 = tmp_finale1[(tmp_finale1["flag_quote"]=='N')|((tmp_finale1["flag_quote"]=='Q')&(tmp_finale1["quota_femminile"].notna()))]
check1 = check1.drop_duplicates(subset='CIG')

In [7]:
der_cig = check1.shape[0]
der_perc = np.round(der_cig/tot_cig*100,2)

In [8]:
print("Ci sono",der_cig,"CIG unici che derogano la norme rispetto alle quote di assunzioni femminili al 30%, su",tot_cig,"CIG unici.")
print("In percentuale:",der_perc,'%')
print(np.round(100-der_perc,2),"% CIG unici che NON derogano la norme rispetto alle quote di assunzioni femminili al 30%.")

Ci sono 111695 CIG unici che derogano la norme rispetto alle quote di assunzioni femminili al 30%, su 170481 CIG unici.
In percentuale: 65.52 %
34.48 % CIG unici che NON derogano la norme rispetto alle quote di assunzioni femminili al 30%.


Ci sono 111695 CIG unici che derogano la norme rispetto alle quote di assunzioni femminili al 30%, su 170481 CIG unici.
In percentuale: 65.52 %
34.48 % CIG unici che NON derogano la norme rispetto alle quote di assunzioni femminili al 30%.

CIG con premialità distribuiti per REGIONE, MISSIONE, IMPORTO

In [60]:
check.columns

Index(['CIG', 'importo_complessivo_gara', 'CLASSE_IMPORTO', 'cod_mis_premiale',
       'misura_premiale', 'CATEGORIA', 'flag_quote', 'quota_femminile',
       'quota_giovanile', 'cod_mot_deroga', 'mot_deroga', 'CUP', 'REGIONE',
       'PROVINCIA', 'COMUNE', 'ANNO_DECISIONE', 'data_pubblicazione',
       'COSTO_PROGETTO', 'IMPORTO_FINANZIAMENTO', 'CODICE_MISSIONE',
       'COMPONENTE', 'INVESTIMENTO', 'MISSIONE'],
      dtype='object')

In [62]:
cig_unici = tmp_finale1.drop_duplicates(subset='CIG')

In [67]:
check # CIG UNICI con premialità di genere
check['REGIONE'].value_counts()
cig_x_reg = pd.DataFrame(cig_unici['REGIONE'].value_counts())
prem_x_reg = pd.DataFrame(check['REGIONE'].value_counts())

In [68]:
cig_x_reg.columns

Index(['count'], dtype='object')

In [70]:
cig_x_reg['REGIONE']

KeyError: 'REGIONE'

In [65]:
#cig_x_reg = pd.DataFrame(data['REGIONE'].value_counts())
cig_x_reg['COUNT'] = cig_x_reg['count']
cig_x_reg['REGIONE'] = cig_x_reg.index
cig_x_reg['REGIONE'] = cig_x_reg['REGIONE'].map(lambda x:str.title(x))

In [66]:
cig_x_reg

count  COUNT                REGIONE
REGIONE                                                   
LOMBARDIA              22193  22193              Lombardia
PIEMONTE               15171  15171               Piemonte
CAMPANIA               12744  12744               Campania
LAZIO                  11898  11898                  Lazio
VENETO                 11413  11413                 Veneto
EMILIA-ROMAGNA         10034  10034         Emilia-Romagna
SICILIA                 9406   9406                Sicilia
TOSCANA                 9197   9197                Toscana
PUGLIA                  8014   8014                 Puglia
CALABRIA                6688   6688               Calabria
MARCHE                  5126   5126                 Marche
SARDEGNA                4596   4596               Sardegna
ABRUZZO                 4458   4458                Abruzzo
LIGURIA                 4352   4352                Liguria
TRENTINO-ALTO ADIGE     3501   3501    Trentino-Alto Adige
FRIULI-VENEZIA GIULIA   2456   2456  Friuli-Venezia Giulia
UMBRIA                  2230   2230                 Umbria
BASILICATA              2002   2002             Basilicata
MOLISE                  1792   1792                 Molise
VALLE D'AOSTA            938    938          Valle D'Aosta

In [52]:
cig_x_reg['REGIONE'] = cig_x_reg['REGIONE'].map(lambda x:str.title(x))
cig_x_reg['COUNT'] = cig_x_reg['REGIONE']
cig_x_reg['REGIONE'] = cig_x_reg.index

In [53]:
cig_x_reg

count                REGIONE                  COUNT
REGIONE                                                                   
LOMBARDIA              22193              LOMBARDIA              Lombardia
PIEMONTE               15171               PIEMONTE               Piemonte
CAMPANIA               12744               CAMPANIA               Campania
LAZIO                  11898                  LAZIO                  Lazio
VENETO                 11413                 VENETO                 Veneto
EMILIA-ROMAGNA         10034         EMILIA-ROMAGNA         Emilia-Romagna
SICILIA                 9406                SICILIA                Sicilia
TOSCANA                 9197                TOSCANA                Toscana
PUGLIA                  8014                 PUGLIA                 Puglia
CALABRIA                6688               CALABRIA               Calabria
MARCHE                  5126                 MARCHE                 Marche
SARDEGNA                4596               SARDEGNA               Sardegna
ABRUZZO                 4458                ABRUZZO                Abruzzo
LIGURIA                 4352                LIGURIA                Liguria
TRENTINO-ALTO ADIGE     3501    TRENTINO-ALTO ADIGE    Trentino-Alto Adige
FRIULI-VENEZIA GIULIA   2456  FRIULI-VENEZIA GIULIA  Friuli-Venezia Giulia
UMBRIA                  2230                 UMBRIA                 Umbria
BASILICATA              2002             BASILICATA             Basilicata
MOLISE                  1792                 MOLISE                 Molise
VALLE D'AOSTA            938          VALLE D'AOSTA          Valle D'Aosta

In [38]:
cig_x_reg['COUNT'] = cig_x_reg['REGIONE']
cig_x_reg['REGIONE'] = cig_x_reg.index
cig_x_reg['REGIONE'] = cig_x_reg['REGIONE'].map(lambda x:str.title(x))

Index(['count'], dtype='object')

In [26]:
np.round(prem_x_reg/cig_x_reg*100,2)

count
REGIONE                     
ABRUZZO                 0.74
BASILICATA              2.30
CALABRIA                2.90
CAMPANIA                3.17
EMILIA-ROMAGNA          3.12
FRIULI-VENEZIA GIULIA   7.33
LAZIO                   3.05
LIGURIA                 1.98
LOMBARDIA               2.59
MARCHE                  2.13
MOLISE                  1.51
PIEMONTE                1.94
PUGLIA                  5.33
SARDEGNA                4.79
SICILIA                 4.87
TOSCANA                 3.52
TRENTINO-ALTO ADIGE     1.37
UMBRIA                  2.38
VALLE D'AOSTA           0.53
VENETO                  3.97

In [27]:
check1 # CIG con deroghe N o Q
check1['REGIONE'].value_counts()
der_x_reg = pd.DataFrame(check1['REGIONE'].value_counts())

In [32]:
np.round(der_x_reg/cig_x_reg*100,2)

count
REGIONE                     
ABRUZZO                72.77
BASILICATA             68.48
CALABRIA               76.99
CAMPANIA               71.30
EMILIA-ROMAGNA         63.61
FRIULI-VENEZIA GIULIA  54.56
LAZIO                  68.80
LIGURIA                69.58
LOMBARDIA              68.54
MARCHE                 63.87
MOLISE                 79.97
PIEMONTE               63.77
PUGLIA                 67.36
SARDEGNA               72.11
SICILIA                63.41
TOSCANA                65.65
TRENTINO-ALTO ADIGE    35.53
UMBRIA                 55.52
VALLE D'AOSTA          43.50
VENETO                 61.14

In [34]:
%pip install -U geopandas

     ---------------------------------------- 0.0/51.1 kB ? eta -:--:--
     ---------------------------------------- 51.1/51.1 kB 2.6 MB/s eta 0:00:00
   ---------------------------------------- 0.0/1.1 MB ? eta -:--:--
   -------- ------------------------------- 0.2/1.1 MB 5.0 MB/s eta 0:00:01
   ----------------- ---------------------- 0.5/1.1 MB 4.9 MB/s eta 0:00:01
   ---------------------- ----------------- 0.6/1.1 MB 4.4 MB/s eta 0:00:01
   ---------------------------- ----------- 0.8/1.1 MB 4.5 MB/s eta 0:00:01
   --------------------------------- ------ 0.9/1.1 MB 3.9 MB/s eta 0:00:01
   ---------------------------------------- 1.1/1.1 MB 3.9 MB/s eta 0:00:00
   ---------------------------------------- 0.0/22.9 MB ? eta -:--:--
   ---------------------------------------- 0.2/22.9 MB 13.0 MB/s eta 0:00:02
    --------------------------------------- 0.5/22.9 MB 5.6 MB/s eta 0:00:04
   - -------------------------------------- 0.6/22.9 MB 5.2 MB/s eta 0:00:05
   - ----------------


[notice] A new release of pip is available: 23.3.2 -> 24.0
[notice] To update, run: C:\Users\Alessandra\AppData\Local\Microsoft\WindowsApps\PythonSoftwareFoundation.Python.3.9_qbz5n2kfra8p0\python.exe -m pip install --upgrade pip


In [35]:
import geopandas as gpd

In [44]:
#Download a geojson of the region geometries
gdf = gpd.read_file(filename=r'https://raw.githubusercontent.com/openpolis/geojson-italy/master/geojson/limits_IT_regions.geojson')
gdf = pd.merge(left=gdf, right=cig_x_reg, how='left', left_on='reg_name', right_on='REGIONE')
gdf.head()

ValueError: 'REGIONE' is both an index level and a column label, which is ambiguous.